breweryorders/breweryorders/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

breweryorders/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

breweryorders/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('beers/', views.beer_list, name='beer_list'),
    path('beers/<str:beer>/',
         views.beer_detail,
         name='beer_detail'),
    path('stock/', views.stock_list, name='product_list'),
    path('stock/<int:id>/', views.product_detail, name='product_detail'),
]

breweryorders/cart/models.py
from django.db import models

# Create your models here.

breweryorders/orders/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Beer(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    description = models.TextField(null=True)
    createdon = models.DateTimeField(auto_now_add=True)
    createdby = models.ForeignKey(User, on_delete=models.PROTECT)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name + " - " + self.type

    def get_absolute_url(self):
        return reverse('orders:beer_detail', args=[self.name])


class Distribution(models.Model):
    PACKAGE_CHOICES = (
        ('butelka', 'Butelka'),
        ('keg', 'Keg'),
    )
    beer = models.ForeignKey(Beer, on_delete=models.CASCADE, related_name='beer_distribution')
    package = models.CharField(max_length=7, choices=PACKAGE_CHOICES, default='butelka')
    capacity = models.DecimalField(max_digits=5, decimal_places=2)
    boxquantity = models.PositiveSmallIntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        ordering = ('beer', 'package',)

    def __str__(self):
        return '{} / {} o pojemności {}l'.format(self.beer, self.package, self.capacity)


class Stock(models.Model):
    AVAILABLE_STATUS = (
        ('dostępne', 'Dostępne'),
        ('ostatnie_sztuki', 'Ostatnie sztuki'),
        ('niedostępne', 'Niedostępne')
    )
    distribution = models.ForeignKey(Distribution, on_delete=models.CASCADE, related_name='beer_stock')
    quantity = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=15, choices=AVAILABLE_STATUS, default="niedostępne")
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('distribution',)

    def __str__(self):
        return 'Zapas {}: {} sztuk'.format(self.distribution, self.quantity)

    def get_absolute_url(self):
        return reverse('orders:product_detail', args=[self.id])


class Lot(models.Model):
    distribution = models.ForeignKey(Distribution, on_delete=models.CASCADE, related_name='beer_lot')
    quantity = models.PositiveIntegerField()
    productiondate = models.DateField()

    class Meta:
        ordering = ('-productiondate',)

    def __str__(self):
        return 'Partia {} o dacie: {}'.format(self.distribution, self.productiondate)


class Order(models.Model):
    STATUS_CHOICES = (
        ('złożone', 'Złożone'),
        ('zrealizowane', 'Zrealizowane'),
        ('anulowane', 'Anulowane'),
    )
    createdon = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='Złożone')
    totalamount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        ordering = ('-createdon',)

    def __str__(self):
        return 'Zamówienie {}'.format(str(self.id).zfill(8))


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_item')
    distribution = models.ForeignKey(Distribution, on_delete=models.PROTECT, related_name='beer_order')
    quantity = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ('-order', 'distribution',)

    def __str__(self):
        return '{} / {}'.format(self.order, self.distribution)

    def save(self, *args, **kwargs):
        try:
            stock = Stock.objects.get(distribution=self.distribution)
            if (stock.quantity < self.quantity):
                print("{} - za mało towaru w magazynie".format(self.distribution))
                return
            else:
                super(OrderItem, self).save(*args, **kwargs)
        except Stock.DoesNotExist:
            print("{} - brak towaru w magazynie".format(self.distribution))
            return

# Create your models here.

breweryorders/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

breweryorders/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from orders.models import Stock
from .cart import Cart
from .forms import CartAddProductForm


# Create your views here.
@require_POST
def cart_add(request, product_id):

    cart = Cart(request)
    product = get_object_or_404(Stock, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Stock, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart=Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

breweryorders/orders/views.py
from django.shortcuts import render, get_object_or_404
from .models import Beer, Distribution, Stock
from cart.forms import CartAddProductForm


# Create your views here.
def beer_list(request):
    beers = Beer.objects.all()
    return render(request,
                  'orders/beer/list.html',
                  {'beers': beers})


def beer_detail(request, beer):
    beer = get_object_or_404(Beer,
                             name=beer)
    return render(request,
                  'orders/beer/detail.html',
                  {'beer': beer})


def stock_list(request):
    products = Stock.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'orders/stock/list.html',
                  {'stock': products,
                   'cart_product_form': cart_product_form})


def product_detail(request, id):
    product = get_object_or_404(Stock, id=id, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'orders/stock/product.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

breweryorders/cart/templates/cart/detail.html
{% extends "orders/base.html" %}
{% load static %}

{% block title %}
Twój koszyk
{% endblock %}

{% block content %}
    <h1>Twój koszyk</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Typ</th>
                <th>Opakowanie</th>
                <th>Pojemność</th>
                <th>Ilość</th>
                <th>Usuń</th>
                <th>Cena jednostkowa</th>
                <th>Kwota</th>
            </tr>
        </thead>
        <tbody>
         {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.distribution.beer.get_absolute_url }}">
                            {{ product.distribution.beer.name }}
                        </a>
                    </td>
                    <td>{{ product.distribution.beer.type }}</td>
                    <td>{{ product.distribution.package }}</td>
                    <td>{{ product.distribution.capacity }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Usuń</a></td>
                    <td> {{ item.price }} PLN</td>
                    <td> {{ item.total_price }} PLN</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Wartość całkowita</td>
            <td colspan="6"></td>
            <td>{{ cart.get_total_price }} PLN</td>
        </tr>
        </tbody>
    </table>
    <p>
        <a href="{% url "orders:product_list" %} "class light">Kontynuuj zamawianie</a>
        <a href="#" class="button">Zakończ zamówienie"</a>
     </p>
{% endblock %}

breweryorders/orders/templates/orders/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static "css/orders.css" %}" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Changa:wght@500&display=swap" rel="stylesheet">

</head>
<body>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
	<div id="sidebar">
		<h2>Koszyk</h2>
			<p>Koszyk jest pusty.</p>
	</div>
</body>
</html>

breweryorders/orders/templates/orders/beer/detail.html
{% extends "orders/base.html" %}

{% block title %}{{ beer.name }}{% endblock %}

{% block content %}
	<h1> {{ beer.name }}</h1>
	<h2 class="type_closer">W stylu {{ beer.type }}</h2>
	<p class="description">
		AAA {{ beer.description }}
	</p>
{% endblock %}
	

breweryorders/orders/templates/orders/beer/list.html
{% extends "orders/base.html" %}

{% block title %}Nasze piwa{% endblock %}

{% block content %}
	<h1>Nasze piwa</h1>
		<table>
		<tr>
			<th>Nazwa</th>
			<th>Typ</th>
		</tr>
	{% for beer in beers %}
		<tr>
			<td><a href="{{ beer.get_absolute_url }}">
			{{ beer.name }}
			</a></td>

		<td><p class="type">
			W stylu {{ beer.type }}
		</p></td>
		<td>
		{{ beer.description|truncatewords:30|linebreaks }}
				</td>
				<td> <input type="button" onclick="alert('{{beer.name}}')" value="Zamów"> </td></tr>
	{% endfor %}
	</table>
	{% include "pagination.html" with page=page_obj %}
{% endblock %}

breweryorders/orders/templates/orders/beer/list2.html
{% extends "orders/base.html" %}

{% block title %}Nasze piwa{% endblock %}

{% block content %}
	<h1>Nasze piwa</h1>
	{% for beer in beers %}
		<h2>
			<a href="{{ beer.get_absolute_url }}">
			{{ beer.name }}
			</a>
		</h2>
		<p class="type">
			W stylu {{ beer.type }}
		</p>
		{{ beer.description|truncatewords:30|linebreaks }}
	{% endfor %}
	{% include "pagination.html" with page=page_obj %}
{% endblock %}

breweryorders/orders/templates/orders/stock/list.html
{% extends "orders/base.html" %}

{% block title %}Piwa dostępe w ofercie{% endblock %}

{% block content %}
	<h1>Piwa aktualnie dostępne w ofercie</h1>
		<table>
			<tableHeader>
				<tr>
					<th bgcolor=""><tableHeader>Nazwa</tableHeader></th>
					<th>Typ</th>
            		<th>Opakowanie</th>
					<th>Pojemność</th>
            		<th>Status</th>
            		<th>Cena</th>
            		<th>Ilość</th>
					<th>pipsztyk</th>
				</tr>
			</tableHeader>

	{% for product in stock %}
		<tr>
			<td><a href="{{ product.distribution.beer.get_absolute_url }}">
			{{ product.distribution.beer.name }}
			</a></td>
			<td>W stylu {{ product.distribution.beer.type }}</td>
			<td>{{ product.distribution.package }}</td>
			<td>{{ product.distribution.capacity }}l</td>
			<td>{{ product.status }}</td>
			<td>{{ product.distribution.price }} PLN</td>
			<!--  <td><input type="button" onclick="alert('{{product.distribution.beer.name}}')" value="Zamów"> </td> */ -->
			<td><button class="open-button" onclick="openForm('{{product.id}}')">Open Form</button></td>
	<td><div class="form-popup" id="myForm">
	  <form action="/action_page.php" class="form-container">
		<h1>Zakup</h1>

			<form action="{% url "cart:cart_add" product_id=product.id %}" method="post">
				{{ cart_product_form }}
				{% csrf_token %}
				<input type="submit" value="Dodaj do zamówienia"> </form>

		<button type="submit" class="btn">Login</button>
		<button type="button" class="btn cancel" onclick="closeForm()">Close</button>
	  </form>
	</div></td>
		</tr>

	{% endfor %}
	</table>

<!--	<div class="form-popup" id="myForm">
	  <form action="/action_page.php" class="form-container">
		<h1>Zakup</h1>

			<form action="{% url "cart:cart_add" product_id=product.id %}" method="post">
				{{ cart_product_form }}
				{% csrf_token %}
				<input type="submit" value="Dodaj do zamówienia"> </form>

		<button type="submit" class="btn">Login</button>
		<button type="button" class="btn cancel" onclick="closeForm()">Close</button>
	  </form>
	</div>-->

	{% include "pagination.html" with page=page_obj %}

	<script>
	function openForm(value) {
	  document.getElementById("myForm").style.display = "block";
	}

	function closeForm() {
	  document.getElementById("myForm").style.display = "none";
	}
	</script>
{% endblock %}

breweryorders/orders/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{page.previous_page_number}}">Poprzednia</a>
		{% endif %}
		<span class="current">
			Strona {{page.number}} z {{page.paginator.num_pages}}.
		</span>
		{% if page.has_next %}
			<a href="?page={{page.next_page_number}}">Następna</a>
		{% endif %}
	</span>
</div>
		